### ISSUE TITLE
Copied?

### ISSUE THREAD

**Issue by KingPixil** [tekotan/Main#6]
Pretty much all of this stuff is copied, for example, your sound maker, is taken from [this pen](http://codepen.io/bgunnison/pen/pgxoG), Cruisin' is taken from [this pen](https://codepen.io/yy/pen/YPjEZw), etc.

So I guess my question is, how is this learning? This is a "way for a middle school student to show his progress", what is the progress? I myself used to learn by simply copying code and playing around with it, but I learned not to. You should try making things **yourself**, this enables you to learn much more.

Check out some of my projects for inspiration (if you need it).

- [Snip - dead-simple URL shortener](https://github.com/KingPixil/snip)
- [Snip for iOS - URL shortening now on your phone](https://github.com/KingPixil/snipApp)
- [Colicious - a delicious color generator](https://github.com/KingPixil/colicious)
- [Lock - self-destructing messages](https://github.com/KingPixil/lock)

See, I had to spend hours working on these, tweaking them as much as possible to make them perfect, and as a result I learned new things. 

Try showing what you know, instead of what others know :smile:

- Kabir Shah

**Comment by tekotan** [comment]
These are just that I have understood the code. It is not real projects yet. I just put it on the web.only some are. Others are understanding and tutorials.

**Comment by KingPixil** [comment]
Well then your website is pretty misleading.

**Comment by tekotan** [comment]
It is not supposed to be live yet.

**Comment by KingPixil** [comment]
But it is....

**Comment by KingPixil** [comment]
Please make an original project!

You must have learned __something__ , show what you have learned :+1:

**Comment by tekotan** [comment]
It is just for GoDaddy domain testing

**Comment by tekotan** [comment]
It is not meant to be viewed. If it is a problem I will remove it from the web for now. Is that fine?

**Comment by KingPixil** [comment]
It seems pretty legit to me, you have declared in each website that you have made it, you should add a notice saying your projects will come out later, it is just a bit confusing right now.

**Comment by tekotan** [comment]
I am very sorry for the confusion

**Comment by KingPixil** [comment]
No problem! Just wanted to let you know :smile:

Looking forward to your projects!
