### ISSUE TITLE
Copied

### ISSUE THREAD

**Issue by FootballCoder** [tekotan/Main#7]
All of the projects on tekotan are copied. I'm too lazy to find the original sites of where you got them from, so I'll only show you a few.

Earth and Sun project - https://codepen.io/juliangarnier/pres/idhuG
Cradle Loader - https://codepen.io/AllThingsSmitty/pen/zxGyXd

Please remove everything you copied and put projects _you_ made!

**Comment by tekotan** [comment]
I am done with process of removing the dummy projects. please refer to the issue at king pixel. i have already done it but forgot to push to github.

**Comment by tekotan** [comment]
I have done that now.

**Comment by tekotan** [comment]
please read the readme.md
